### ISSUE TITLE
Support Kafka Interceptors for general Producer Consumer support

### ISSUE THREAD

**Issue by bluemonk3y** [cloudevents/sdk-java#100]
Kafka Interceptors have full access to Header, K, V and would allow the Marshaller to proxy the event and map to/from the wire format. This approach would mean CE can be plugged into existing Kafka applications and applied across all supported Kafka Client language bindings for CE sdks.

**Comment by fabiojose** [comment]
@bluemonk3y looks nice, please consider a PR for that.

**Comment by slinkydeveloper** [comment]
Hi, since producer/consumer are removed from 2.0.0-SNAPSHOT, this one is invalid

**Comment by bluemonk3y** [comment]
@slinkydeveloper  - how do you write to Kafka without the Producer or Consumer?

**Comment by slinkydeveloper** [comment]
The idea is that you use the producer and consumers from the kafka library, but you set the serializer/deserializer this library provide. look at this example: https://github.com/cloudevents/sdk-java/tree/master/kafka#producing-cloudevents

**Comment by bluemonk3y** [comment]
How does a serializer write or read the Kafka record header?

**Comment by slinkydeveloper** [comment]
the serializer gets a writable kafka record headers: https://github.com/cloudevents/sdk-java/blob/master/kafka/src/main/java/io/cloudevents/kafka/impl/BaseKafkaMessageVisitorImpl.java#L38
