### ISSUE TITLE
Support java1.7

### ISSUE THREAD

**Issue by zd-double** [cloudevents/sdk-java#101]
There's lots of usage of java8 in sdk-java like ZonedDateTime, Is there an adaptor version for Java7

**Comment by fabiojose** [comment]
@zd-double, nope, no adapter for java7.

Are you have using java7?

**Comment by slinkydeveloper** [comment]
Java 7 is from long time out of LTS support, so I think we're not going to support it, since it's too complex and too hard to mantain
