### ISSUE TITLE
incorrect content-length in http-vertx

### ISSUE THREAD

**Issue by matejvasek** [cloudevents/sdk-java#103]
The http-vertx determines content-length by String.length() which returns count of characters byte size.

**Comment by slinkydeveloper** [comment]
This one still applies? Or can we close it?

**Comment by slinkydeveloper** [comment]
@matejvasek ping

**Comment by matejvasek** [comment]
@slinkydeveloper since it uses response.end() instead of response.write() it should be fixed.

**Comment by slinkydeveloper** [comment]
Thank you! Reopen if you need it.
