### ISSUE TITLE
Content Type being filtered out at the consumer

### ISSUE THREAD

**Issue by CH-karthikprasad** [cloudevents/sdk-java#117]
Hey, 

I have been trying to use CloudEvents along with Kafka. For the message format, I am using Avro.
I am using the java sdk version 1.3.0 with the CloudEvent producers and consumers.

My observation.
In the HeaderMapper.java class `https://github.com/cloudevents/sdk-java/blob/361a34cc639ddaa75b2a5080f117fc282be7625b/kafka/src/main/java/io/cloudevents/v1/kafka/HeaderMapper.java#L53`, you are filtering out the `datacontenttype` from being mapped to a header prefixed with `ce`. Then, later `https://github.com/cloudevents/sdk-java/blob/361a34cc639ddaa75b2a5080f117fc282be7625b/kafka/src/main/java/io/cloudevents/v1/kafka/HeaderMapper.java#L76`, you add to the headers using `content-type`. So, after the marshalling the key in the header is `content-type`. Now, when this header is consumed by a consumer and unmarshalled (I am using the binary unmarshaller) the header, the `content-type` header is filtered here `https://github.com/cloudevents/sdk-java/blob/361a34cc639ddaa75b2a5080f117fc282be7625b/kafka/src/main/java/io/cloudevents/v1/kafka/AttributeMapper.java#L60`. After this, when the `AttributeImpl` object is created through this method `https://github.com/cloudevents/sdk-java/blob/242b58a5309d319d24a907077e553c19d15a54fe/api/src/main/java/io/cloudevents/v1/AttributesImpl.java#L182`, the `datacontenttype` is not a field within the `attributes` map. Then, when the data is being deserialized, the code calls `getMediaType()` on the `AttributeImpl` object `https://github.com/cloudevents/sdk-java/blob/361a34cc639ddaa75b2a5080f117fc282be7625b/api/src/main/java/io/cloudevents/format/BinaryUnmarshaller.java#L222`, it gets a `null` object. And the data is not being deserialized. 

Am i using the sdk in the wrong way ? It would be great to get an example for the Avro Kafka piece with this sdk.

**Comment by CH-karthikprasad** [comment]
I think this issue is the same as https://github.com/cloudevents/sdk-java/issues/88.

I will close this one when confirmed. Thanks

**Comment by slinkydeveloper** [comment]
I think this one is invalid with 2.0.0-SNAPSHOT
