### ISSUE TITLE
Common entry point

### ISSUE THREAD

**Issue by bsideup** [cloudevents/sdk-java#120]
Since the spec evolves, new versions of the spec are being added (think 0.2, 0.3, 1.0)

At the moment, it is the responsibility of the end user - to figure out from the input (e.g. HTTP request) which spec version was used to encode the event before calling the unmarshaller.

It _feels_ that this (not trivial) responsibility should be handled by the SDK itself and provide a generic method to "just read the CloudEvent", that will read the headers (or parse the JSON object if in structured mode) and figure out which *implementation* should be used.

This way, adding a support for a newer version of the spec should be as easy as updating the SDK dependency.

**Comment by slinkydeveloper** [comment]
This should be solved by #108, but we'll revisit it after to figure out if we have any leftovers

**Comment by bsideup** [comment]
@slinkydeveloper could you please describe here (in text and/or code snippets) how do you plan to solve it? I believe it will help to define the migration path for those who are already on v1 and need to plan it now.

**Comment by slinkydeveloper** [comment]
As  #108;

### Json and other event formats

To marshal/unmarshal event formats, the user just asks to the `EventFormatProvider` to provide resolve a format, and the `EventFormat` implementation takes care of correctly implementing marshal/unmarshal for different event versions (this is highly simplified by the `Message` interface)

### HTTP

In sdk v1 there was this concept of `Unmarshaller` which is removed.

Now the APIs to marshal/unmarshal back/forth the wire resembles the one from sdk-go/sdk-rust, but leveraging generics. Now an HTTP implementation (let's take Vert.x as example) implements the interfaces `Message` to _read_ the event from the wire and `write` to write the event to the wire (naming is still temporary):

```
VertxMessage msg = new VertxMessage(httpReq);
CloudEvent ev = msg.toEvent();
```

```
VertxMessageVisitor res = new VertxMessageVisitor(httpResponse);
event.asBinaryMessage().visit(res);
// or
event.asStructuredMessage(jsonFormat).visit(res);
```

**Comment by slinkydeveloper** [comment]
@bsideup does this API solve the problem, or do you think we still miss something?

**Comment by slinkydeveloper** [comment]
To me this one looks solved, reopen if you need it
