### ISSUE TITLE
Add examples

### ISSUE THREAD

**Issue by slinkydeveloper** [cloudevents/sdk-java#125]
We need an examples directory with ready to try projects, which contains some examples on how to use our integrations:

* [x] An example using http with vertx #195
* [x] amqp https://github.com/cloudevents/sdk-java/pull/294
* [x] An example using http with restful ws
  * [x] resteasy #226
  * [x] spring boot #288
* [x] An example using kafka #194
* [x] Readme that explains the examples https://github.com/cloudevents/sdk-java/pull/298

These samples should also show how to use the event builder, how to access the event and the other basic features of cloudevents-core (maybe we need another example just showing these functionalities?).

Most of these examples can be "extracted" from the tests and the modules READMEs, we just need to clean them up and comment it.

If you're going to work on one of the examples underlined above, please write it down in the comments.

**Comment by pierDipi** [comment]
I can work on `"An example using http with vertx"`.

**Comment by cmoulliard** [comment]
Having such `examples` or `HowTo` guides will help the developers/architects to figure out what finally they could design using CloudEvents, Java SDK.

**Comment by slinkydeveloper** [comment]
#226 adds a sample with restful-ws + quarkus

**Comment by slinkydeveloper** [comment]
I'm gonna work on the readme that lists the various samples
