### ISSUE TITLE
master branch is broken

### ISSUE THREAD

**Issue by bsideup** [cloudevents/sdk-java#128]
#108 just broke the master build:
https://travis-ci.org/github/cloudevents/sdk-java/jobs/678133008

It would suggest reverting it and re-applying, but it wasn't squashed into a single commit neither, which would mean reverting 21 commit.

**Comment by slinkydeveloper** [comment]
Fixed by https://github.com/cloudevents/sdk-java/pull/127, weird that CI didn't noticed...
