### ISSUE TITLE
Remove cdi module

### ISSUE THREAD

**Issue by slinkydeveloper** [cloudevents/sdk-java#139]
Since cdi looks unused from the maven central stats and it doesn't add a lot of value to the project, i propose to remove it. 

@bsideup @fabiojose @matzew any takes on this?

![chart](https://user-images.githubusercontent.com/6706544/80475598-5f237a80-8949-11ea-9fbd-3cab704fa18c.png)

![chart](https://user-images.githubusercontent.com/6706544/80475660-7c584900-8949-11ea-893f-40b11ca535cc.png)

**Comment by bsideup** [comment]
I think that's a good idea. IMO it does not belong here.
