### ISSUE TITLE
Create a minimal cloudevents artifact without external dependencies

### ISSUE THREAD

**Issue by johanhaleby** [cloudevents/sdk-java#168]
Hi, 

I just tried to cloudevents java SDK version 1.3.0:

```xml
<dependency>
  <groupId>io.cloudevents</groupId>
  <artifactId>cloudevents-api</artifactId>
  <version>1.3.0</version>
</dependency>
```

but to my surprise it contained several versions of the cloud events specification as well as several external dependencies such as jackson, hibernate-validation etc. I'm sure this is fine for many people but I would appreciate a cloudevent dependency with only a minimal set of classes/interfaces required for the 1.0 version. The `cloudevents-api` could then depend on this module to add the validation and serialization properties for conveniency.

 I see in the [README](https://github.com/cloudevents/sdk-java/blob/master/README_v1.md) that one should depend on:

```xml
<dependency>
    <groupId>io.cloudevents</groupId>
    <artifactId>cloudevents-core</artifactId>
    <version>1.3.0</version>
</dependency>
```

but I cannot seem to find this artifact in [maven central](https://search.maven.org/search?q=cloudevents-core) which is why I went for `cloudevents-api`.  Maybe this is the artifact that I'm looking for? If so is there a reason for why it's not published to maven central?

Regards,
/Johan

**Comment by slinkydeveloper** [comment]
Hi @johanhaleby, we're actually working on a new version of the sdk that will be composed by:

* cloudevents-api: 0 deps, only interfaces
* cloudevents-core: 0 deps, only implementations of interfaces in cloudevents-api
* formats/*: implementations of event formats with various libraries (for now we have only jackson)
* http/*: implementations of http protocol bindings
* cloudevents-kafka: implementation of kafka protocol binding

All these packages are fully independent and you won't have anymore the problem of downloading a "fat module" for using only some sdk features. Does that solve your problem?

**Comment by johanhaleby** [comment]
@slinkydeveloper Yes it sounds like it does. Thanks for your reply and for the great work :) Looking forward to the new version.
