### ISSUE TITLE
Format is null

### ISSUE THREAD

**Issue by doru1004** [cloudevents/sdk-java#169]
I am using the latest version and when I do this:

```
EventFormat format = EventFormatProvider
  .getInstance()
  .resolveFormat("application/json");
```

format is null.

How can I fix this?

**Comment by slinkydeveloper** [comment]
`application/json` is not a cloudevent format. The format is resolved by its content-type, in the case of json event format `application/cloudevents+json` as explained https://github.com/cloudevents/spec/blob/v1.0/json-format.md#3-envelope

**Comment by doru1004** [comment]
Regardless of which format I use, the result is the same, format is null.

```
EventFormat format = EventFormatProvider
  .getInstance()
  .resolveFormat("application/json");
```

```
EventFormat format = EventFormatProvider
  .getInstance()
  .resolveFormat("application/cloudevents+json");
```

**Comment by slinkydeveloper** [comment]
Now jackson is not included anymore in the sdk, you need to bring it as additional dependency `cloudevents-json-jackson`: https://github.com/cloudevents/sdk-java/tree/master/formats/json-jackson

**Comment by doru1004** [comment]
That worked! Thanks a lot!
