### ISSUE TITLE
Consider removing "get" prefixes on CloudEvent and other related interfaces

### ISSUE THREAD

**Issue by sparty02** [cloudevents/sdk-java#171]
Consider simply using the attribute names in the CloudEvent and CloudEventAttributes interfaces (others as appropriate).  Other parts of the ecosystem (Immutables, AutoValue, and now Java Records) have encouraged simply using the field name as the "getter" for these kinds of value types.

```java
public interface CloudEventAttributes {
    SpecVersion specVersion();
    String id();
    String type();
    // ...
}
```

Going a step further, you could also consider changing the builders to remove some verbosity as well, e.g.

```java
public interface CloudEventBuilder extends CloudEventVisitor<CloudEvent> {
    CloudEventBuilder id(String id);
    CloudEventBuilder source(URI source);
    // ...
```

Once you get used to it, it is very readable and allows for fluent building to be a bit more terse.

**Comment by slinkydeveloper** [comment]
For what regards getters, I just tried locally and what I don't like is that it doesn't interop well with Kotlin. In Kotlin `get*` method are automatically translated in field accessors (in kotlin way), if you name it `specVersion()` the Kotlin compiler won't recognize it automatically (https://kotlinlang.org/docs/reference/java-interop.html#getters-and-setters)

For the setters in `CloudEventBuilder`, this sounds like a good idea, mind doing a PR?

**Comment by slinkydeveloper** [comment]
I would love to hear input from other users, since this is a quite important discussion

**Comment by pierDipi** [comment]
+1 for this proposal, in particular, the usage of the CloudEventBuilder is too verbose with all those `with*`.

**Comment by bsideup** [comment]
+ the same issue (field-like access) will also happen with Groovy.

IMO the current approach (`getX`) is good enough and idiomatic. It also helps to distinguish get/set semantics when the method references are used (`event::getId`).

**Comment by markfisher** [comment]
Regarding the getX methods, I agree with @slinkydeveloper and @bsideup: getters on the interface are idiomatic (and relied upon for frameworks/tools).

While "withX" is also fairly idiomatic for Java builders, I think it would be ok to make those more concise since - at least so far - the only other prefixed operation is a _static_ "fromX". If there were more/other prefixed operations, the "with" might be worth keeping to help differentiate the settable properties, especially when using auto-completion.

**Comment by slinkydeveloper** [comment]
It seems to me the majority agrees on keeping the existing names, If somebody else is interested in this topic then feel free to reopen the issue again
