### ISSUE TITLE
Consider making the constructor of CloudEventSerializer and CloudEventDeserializer public

### ISSUE THREAD

**Issue by johanhaleby** [cloudevents/sdk-java#197]
When creating a custom marshaller/unmarhaller that returns something other than `byte[]` if would be helpful to make use of the already existing `CloudEventSerializer` and `CloudEventDeserializer` from `cloudevents-json-jackson`. But currently the constructors in these two classes are `protected` which makes it look a bit awkward since you have to instantiate them like this:

```java
new CloudEventSerializer() {};
``` 

For reference see discussions in [issue 196](https://github.com/cloudevents/sdk-java/issues/196).

**Comment by slinkydeveloper** [comment]
@johanhaleby How about using directly `JsonFormat#getJacksonModule`?

**Comment by johanhaleby** [comment]
That would probably work, missed that :) Thank you!
