### ISSUE TITLE
Add support for making changes to a CloudEvent instance

### ISSUE THREAD

**Issue by johanhaleby** [cloudevents/sdk-java#199]
I have a use case in which I'd like to add an extension to an existing CloudEvent. This is actually quite difficult, in my case, it looks like this currently:

```java
CloudEvent otherCloudEvent = ..

// I want to add an extension property, "x", to otherCloudEvent. But to this this I first need to clone it:
CloudEventBuilder b = new CloudEventBuilder()
        .withId(otherCloudEvent.getId())
        .withSource(otherCloudEvent.getSource())
        .withDataSchema(otherCloudEvent.getDataSchema())
        .withSubject(otherCloudEvent.getSubject())
        .withTime(otherCloudEvent.getTime())
        .withType(otherCloudEvent.getType())
        .withDataContentType(otherCloudEvent.getDataContentType())
        .withData(otherCloudEvent.getData());

otherCloudEvent.getExtensionNames().forEach(name -> {
    Object value = otherCloudEvent.getExtension(name);
    if (value instanceof String) {
        b.withExtension(name, (String) value);
    } else if (value instanceof Boolean) {
        b.withExtension(name, (boolean) value);
    } else if (value instanceof Number) {
        b.withExtension(name, (Number) value);
    }
});

// Now I can finally add "x"
b.withExtension("x", "y");

CloudEvent newCloudEvent = b.build();
```

Which is very verbose (and only supports spec version 1). 

It would be nice if it was be possible to "change" properties of a cloud event. But when I say "change" I want to emphasize  that I don't mean a mutable change but rather something similar to data classes in Kotlin. But given that `CloudEvent` is an interface it would probably make sense to not include this functionality in `cloudevents-api`. Maybe a completely new module would be the best option whose purpose is solely dealing with immutable updates of a `CloudEvent`?

Or maybe this is totally out of scope? I think that's a reasonable stance as well. 

WDYT?

**Comment by slinkydeveloper** [comment]
Hi @johanhaleby, we decided in past to keep the `CloudEvent` interface immutable, but you don't need to copy manually the fields from one event to the builder. You can use these copy builders: https://github.com/cloudevents/sdk-java/blob/master/core/src/main/java/io/cloudevents/core/builder/CloudEventBuilder.java#L180 Is that what you need?

**Comment by johanhaleby** [comment]
@slinkydeveloper Oh I've completed missed that method! That's great! 

Thanks for the pointer and sorry for the fuss :)

**Comment by slinkydeveloper** [comment]
Don't worry! :wink:
