### ISSUE TITLE
Fix repository description

### ISSUE THREAD

**Issue by joschi** [cloudevents/sdk-java#2]
The repository description on GitHub and the stub README currently say: "Javascript SDK for CloudEvents"

Given the name of the repository (sdk-java) and the first PR (#1), I guess that it should be "Java SDK for CloudEvents".

**Comment by matzew** [comment]
@joschi yes, I saw that too. unfortunately I am not able to change that.

@duglin can you fix the GH repo description ?

**Comment by duglin** [comment]
Fixed!
