### ISSUE TITLE
Switch `ZonedDateTime` to `OffsetDateTime`

### ISSUE THREAD

**Issue by pwall-tyro** [cloudevents/sdk-java#214]
The cloudevents spec clearly [says](https://github.com/cloudevents/spec/blob/v1.0/spec.md#time) that the `time` attribute "MUST adhere to the format specified in [RFC 3339](https://tools.ietf.org/html/rfc3339)".  The `java.time.xxx` class that corresponds to RFC 3339 is `OffsetDateTime`.

`ZonedDateTime` adds a time zone identifier (in the form of region/city) to the end of the string on serialization, meaning that an event containing a time output by normal serialization does not conform the the spec.

`OffsetDateTime` is easier to work with, takes less space and more correctly implements the spec.

**Comment by slinkydeveloper** [comment]
Hi @pwall-tyro, thanks for catching up this issue, mind doing a PR for it?
