### ISSUE TITLE
CloudEvents with Avro payloads, on Kafka

### ISSUE THREAD

**Issue by mnuttall** [cloudevents/sdk-java#238]
My team is looking at sending Avro-encoded cloud events over Kafka, often to or from Apache Camel-K. We’ve done some prototyping in which we’ve had to combine the Cloud Events Java SDK with the io.confluent.kafka Serde library. This leaves message receivers having to choose between the CloudEvent and Confluent deserializers since the former unpacks the headers nicely but produces an encoded payload, and the latter decodes the payload but leaves you to manage the headers yourself. 

This is different from the [Avro format for CloudEvents](https://github.com/cloudevents/spec/blob/v1.0/avro-format.md) which describes a CloudEvent in Avro - we want to do the opposite, sending a binary, Avro-encoded payload with headers as per the [Kafka Protocol Binding for CloudEvents](https://github.com/cloudevents/spec/blob/v1.0/kafka-protocol-binding.md). 

In [this Slack thread](https://cloud-native.slack.com/archives/CCXF3CBL1/p1601046799007500) I wondered, 

> (For example, one could pass `io.confluent.kafka.serializers.KafkaAvroDeserializer` to `io.cloudevents.kafka.CloudEventDeserializer` as something to delegate body-deserialization to, perhaps.) 

@slinkydeveloper stated, 
 
> That sounds like an interesting problem, there is no official answer from the sdk to the problem "body decoding". This was left out from the sdk design by purpose, in order to avoid making complex abstractions on top of marshallers/unmarshallers and/or opinionated choices. [...] Your solution of "delegation" for the kafka deserializer looks like an interesting choice. However, It solves the particular problem only for kafka: I would love to find a solution that can be applied in all the other reader/writers. 

He also mentioned [Issue 196](https://github.com/cloudevents/sdk-java/issues/196) as being somewhat related to this question. 

I would like to provide a nice way of handling messages with as much CloudEvents, schema management and de/serialization support built in as possible. Currently our prototype code has two layers: one using the CloudEvent APIs for handling the envelope then a second using Confluent APIs for handling the payload. Can anyone see a better way of doing this? Many thanks in advance for any suggestions!

**Comment by slinkydeveloper** [comment]
I wonder if adding some "mapper" api like `CloudEvent#getData<T>(Function<Something, T>)` can at least ease the issue you're experiencing here.

**Comment by slinkydeveloper** [comment]
This problem is kinda orthogonal to the one described in #198 but i see how we can find a solution to both problems at the same time

**Comment by slinkydeveloper** [comment]
@mnuttall the new `CloudEventData` api should allow you to store your business object inside the `CloudEvent`. At this point, i think what we miss is the "wrapper"/"decorator" that can be invoked, starting from `io.cloudevents.kafka.CloudEventDeserializer`, to perform the deserialization of the payload
