### ISSUE TITLE
Remove UnknownEncodingMessageReader and replace with exceptions

### ISSUE THREAD

**Issue by slinkydeveloper** [cloudevents/sdk-java#262]
* Remove `UnknownEncodingMessageReader` and, in `MessageUtils#parseStructuredOrBinaryMessage`, replace the unknownMessageFactory with a `CloudEventRWException`
* Removed `Encoding#UNKNOWN` variant since it won't be useful anymore

**Comment by smadasu** [comment]
@slinkydeveloper TBH, I don't even see the need for this class at all. There is no functionality in the class except throwing exceptions for any method call. This class should be removed and CloudEventRWException should be thrown at the places where this is instantiated.

**Comment by slinkydeveloper** [comment]
Makes sense, do you wish to contribute it @smadasu?

**Comment by smadasu** [comment]
Sure @slinkydeveloper  . I will create a PR for this.

**Comment by slinkydeveloper** [comment]
Solved by #277
