### ISSUE TITLE
BaseCloudEvent#readExtensions does not support DatarefExtension

### ISSUE THREAD

**Issue by wong-git** [cloudevents/sdk-java#266]
Marked as general TODO, but it should handle `URI` since that is the type of the value for a `DatarefExtension`

**Comment by slinkydeveloper** [comment]
Sorry, are you proposing to handle `URI` as a type in `CloudEventAttributes`?

**Comment by wong-git** [comment]
Not in `CloudEventAttributes` but in the existing `DatarefExtension`. This is an example of the code:
```
var cloudEventBuilder = CloudEventBuilder.v1();
...
var datarefExtension = new DatarefExtension();
datarefExtension.setDataref(URI.create(...));
cloudEventBuilder.withExtension(datarefExtension);
return new ProducerRecord<>(topic, key, cloudEventBuilder.build());
```
But this then results in `BaseCloudEvent#readExtensions` throwing `IllegalStateException` because the `DatarefExtension`s value is a `URI`.

Just to note, `DatarefExtension` supports conversion on deserializing by taking the `String` value in the Kafka headers and converting that to a `URI`.

**Comment by slinkydeveloper** [comment]
This definitely sounds like a bug, `DatarefExtension#getValue` should return only valid extension types (String, Boolean or Number). Can you provide a fix for it?

**Comment by slinkydeveloper** [comment]
Explicited the return types in the javadoc too https://github.com/cloudevents/sdk-java/pull/267/commits/b68f58595aa50f2d9fdf6357ab15310c0282f161

**Comment by wong-git** [comment]
By "provide" I'm guessing you mean submit a PR for it. Will do.
