### ISSUE TITLE
CloudEventBuilder should fail when providing an invalid extension name

### ISSUE THREAD

**Issue by slinkydeveloper** [cloudevents/sdk-java#271]
The `CloudEventBuilder` should fail with the proper exception (look at `CloudEventRWException#newInvalidExtensionName`) if the user is trying to add an extension with a bad name (as specified here https://github.com/cloudevents/spec/blob/master/spec.md#attribute-naming-convention)

**Comment by arghya88** [comment]
@slinkydeveloper So `withExtension` need to be overridden like `withAttribute` in `CloudEventBuilder` to achieve this?

**Comment by slinkydeveloper** [comment]
WDYM needs to be overriden? This issue is just about changing the impl of `CloudEventBuilder` to check the name of the extension: https://github.com/cloudevents/sdk-java/blob/master/core/src/main/java/io/cloudevents/core/impl/BaseCloudEventBuilder.java#L99

**Comment by arghya88** [comment]
My bad...Understood now
/assign
