### ISSUE TITLE
Don't allow null `CloudEventDataMapper`

### ISSUE THREAD

**Issue by eamonnmcmanus** [cloudevents/sdk-java#285]
I was starting to log an issue about a NullPointerException in Milestone 4 when I discovered that @matejvasek had already fixed it in #259. I'd like to suggest that other similar NPEs could be avoided if we didn't allow the mapper in [`MessageReader.toEvent(CloudEventDataMapper)`](https://www.javadoc.io/static/io.cloudevents/cloudevents-core/2.0.0-milestone4/io/cloudevents/core/message/MessageReader.html#toEvent-io.cloudevents.rw.CloudEventDataMapper-) to be null. There's no reason to allow that, and it's just setting a trap. If you don't need to map the data then just supply an identity mapper. The no-arg [`MessageReader.toEvent()`](https://www.javadoc.io/static/io.cloudevents/cloudevents-core/2.0.0-milestone4/io/cloudevents/core/message/MessageReader.html#toEvent--) could call `toEvent(data -> data)` instead of `toEvent(null)`. And a bunch of `if (mapper == null)` code could presumably be removed.

**Comment by slinkydeveloper** [comment]
@eamonnmcmanus do you want to propose a fix for it?

**Comment by slinkydeveloper** [comment]
When `toEvent()` is called, maybe we could just provide a noop mapper down in the reader

**Comment by slinkydeveloper** [comment]
@eamonnmcmanus wanna review this one? https://github.com/cloudevents/sdk-java/pull/286 thanks!
