### ISSUE TITLE
Enable Travis CI build

### ISSUE THREAD

**Issue by matzew** [cloudevents/sdk-java#3]
Hi @duglin 

I am not able to enable the build on Travis CI for this project.

Can you either do that or grant me the right permission for this repo? 

Link to travis:
https://travis-ci.org/organizations/cloudevents/repositories

**Comment by duglin** [comment]
I think it's done now - give it a try

**Comment by matzew** [comment]
Thank you, sir!

see our first cI build: https://travis-ci.org/cloudevents/sdk-java/builds/452697047

closing this :tada:
