### ISSUE TITLE
Decouple the Event Context from CloudEvent

### ISSUE THREAD

**Issue by slinkydeveloper** [cloudevents/sdk-java#311]
Although we have `CloudEventContext`, today user can't still interact only with `CloudEventContext`. This is particularly relevant in the discussions happening around the Spring support #302

Open questions:

* Should `io.cloudevents.rw` support reading/writing only a `CloudEventContext` without building the full `CloudEvent`?
* Should `CloudEventBuilder` have the context building abstracted away to build only a `CloudEventContext`?
* MessageReader/MessageWriter: how should we deal with structured messages? Say, I get a CloudEvent in structured mode from http and i want to build only the `CloudEventContext`, what do I do with the payload?

**Comment by pierDipi** [comment]
This issue seems obsolete / not relevant anymore, closing.
