### ISSUE TITLE
Spec defines field names following lowercase convention but when serializing to json it generates camelCase fieldNames

### ISSUE THREAD

**Issue by maiconmattos** [cloudevents/sdk-java#32]
Spec defines field names following lowercase convention : 
https://github.com/cloudevents/spec/blob/v0.2/spec.md#specversion

But when serializing to json it generates camelCase fieldNames.

Possible solution :
@JsonNaming(LowerCaseStrategy.class)
public class DefaultCloudEventImpl<T> implements CloudEvent<T>, Serializable {

Also, no unit test for Json serialization.

**Comment by Raytan** [comment]
Meet the same issue: I use fastjson which uses getters list to set the key name of json map.
Is there a reason why use lowercase instead of camelCase?

**Comment by micheleangioni** [comment]
Hi guys,
we are facing the same issue, which is causing us troubles.
@matzew @jponge @fabiojose could you please take a look?

Thanks.

**Comment by fabiojose** [comment]
@micheleangioni  Job done!

What do you think about to perform a code review?

PR #42
