### ISSUE TITLE
CloudEvent.toString() should not include null attributes

### ISSUE THREAD

**Issue by wlaforest** [cloudevents/sdk-java#326]
I have only checked io.cloudevents.core.v1.CloudEventV1 but rather than concatenation null values for optional attributes they should be omitted.  I am open to fixing this and doing a pull request if this is preferred.. potentially its already fixed in a branch?  Thank you everyone for the work.

**Comment by slinkydeveloper** [comment]
Hi, you can go ahead and open a PR for it, thanks for spotting it!

**Comment by edmondop** [comment]
@slinkydeveloper  hello you. Can you explain why the CloudEvent constructor is public rather than being package protected?
