### ISSUE TITLE
Backwards compatibility future plans

### ISSUE THREAD

**Issue by razorcd** [cloudevents/sdk-java#33]
Thank you for this great library. We have integrated CloudEvents in our system already and would like to start using this library too.

There were some breaking changes between v0.1 and v0.2 in the CloudEvents specs and I see that at the moment `cloudevents/sdk-java` is backwards compatible. ([example](https://github.com/cloudevents/sdk-java/blob/master/api/src/main/java/io/cloudevents/impl/DefaultCloudEventImpl.java#L114))

But since these are versions before the major version v1.0, could you please tell me if you intend to always keep backwards compatibility in the future for any new versions of CloudEvents specs (for any future breaking changes)?

It is important for us to be able to gradually update our events with every new CloudEvent version. This results in a Kafka topic with multiple versions of CloudEvents. To avoid creating custom adapters, it would be great to only rely on the `cloudevents/sdk-java` library no matter which version of CloudEvents we use.

Thanks,
Cristian

**Comment by fabiojose** [comment]
At this moment all SDKs are working in version 1.0.0

After this milestone, we have plans to release versions with almost no break compatibility.

But until there, breaking is inevitable.

At this moment we released version 0.3.0, that is incompatible with releases before.

**Comment by bsideup** [comment]
The by-version split indeed makes it harder to rely on CloudEvents because one has to re-implement the logic to parse the spec version header and select an appropriate builder.

Another thing is that some parameters that are set in stone (from the v1 spec, like `time`) are not in the `CloudEvent` interface, and the only option to get them is to cast to `CloudEventImpl` from `v1` package.

@fabiojose would you consider deprecating 0.x versions and syncing `CloudEvent` with v1?

**Comment by matzew** [comment]
I like the idea of deprecation.

and perhaps add some function to go from `0.x` -> `1.0` as a conversion hook

**Comment by slinkydeveloper** [comment]
Hi!
In SDK v2 we added methods to convert events back/forth different spec versions (in sdk v2 the only supported will be 0.3 and 1.0). The sdk v2 won't be compatible with sdk v1, since the major changes introduces to vastly simplify usability.

**Comment by razorcd** [comment]
IMO all major versions should be backwards compatible. Upgrading services to publish/consume new version of the CloudEvents is done one stream at a time. In a distributed system it is almost impossible to update all producers and consumers at the same time.

Without backwards compatibility we will have to manually import multiple versions of the SDK in the same application. Not even sure what conflicts this could create. And with frameworks like Spring that rely on IOC, meaning a Singleton to handle the entire serialization/deserialization it would require a workaround to handle multiple CloudEvent versions.

**Comment by slinkydeveloper** [comment]
> IMO all major versions should be backwards compatible. Upgrading services to publish/consume new version of the CloudEvents is done one stream at a time. In a distributed system it is almost impossible to update all producers and consumers at the same time.

I'm sorry, I explained myself badly. Both sdk 1.x and 2.x supports cloudevents spec versions 0.3 and 1.0, so they should be able to talk each other, if that's what you mean. APIs however will be different, in order to simplify the usage of the sdk

**Comment by eamonnmcmanus** [comment]
Is there a planned release date for the 2.0.0 API? I'd like to use it to [add CloudEvents support](https://github.com/GoogleCloudPlatform/functions-framework-java/issues/37) to the GCP Functions Framework for Java. 1.3.0 doesn't have the same clean separation between API and implementation, so using it would imply pulling in a bunch of implementation dependencies, as well as requiring us to make a second version later to allow for the incompatible API changes in 2.0.0.

**Comment by slinkydeveloper** [comment]
> Is there a planned release date for the 2.0.0 API?

Not yet, I hope as soon as we stabilize a bit the APIs we can release a milestone. Keep in touch :wink:

**Comment by slinkydeveloper** [comment]
Can we close this issue?

**Comment by slinkydeveloper** [comment]
BTW we have an explanation of the CloudEvents spec versions an sdk should support https://github.com/cloudevents/spec/blob/master/SDK.md#contribution-acceptance
