### ISSUE TITLE
io.cloudevents.rw.CloudEventRWException: Invalid specversion: 0.2

### ISSUE THREAD

**Issue by boblee0717** [cloudevents/sdk-java#330]
I got this exception: io.cloudevents.rw.CloudEventRWException: Invalid specversion: 0.2

Is there a way to workaround this?

`2020-12-11 18:05:08.521 CST - io.cloudevents.rw.CloudEventRWException: Invalid specversion: 0.22020-12-11 18:05:08.522 CST -
2020-12-11 18:05:08.522 CST - 	at io.cloudevents.rw.CloudEventRWException.newInvalidSpecVersion(CloudEventRWException.java:91)
	at io.cloudevents.SpecVersion.parse(SpecVersion.java:76)2020-12-11 18:05:08.522 CST -
2020-12-11 18:05:08.522 CST - 	at io.cloudevents.core.message.impl.MessageUtils.parseStructuredOrBinaryMessage(MessageUtils.java:58)
2020-12-11 18:05:08.522 CST - 	at io.cloudevents.http.HttpMessageFactory.createReader(HttpMessageFactory.java:78)`

**Comment by slinkydeveloper** [comment]
This is expected, the sdk v2 doesn't support cloudevents spec 0.1 and 0.2. It supports only 0.3 and 1.0 (as majority of cloudevents sdks today)

**Comment by boblee0717** [comment]
> This is expected, the sdk v2 doesn't support cloudevents spec 0.1 and 0.2. It supports only 0.3 and 1.0 (as majority of cloudevents sdks today)

Thanks for your answer. However, the event producer can not change the version immediately, is there any way to workaround this?

**Comment by slinkydeveloper** [comment]
I don't think there is a workaround with the sdk v2, not sure if sdk v1 supports it... Note that 0.2 is EOL for all sdks, so i guess you should focus on updating the event producer asap. Or you can develop a service using older sdks (like sdk-go) to translate events to newer version.

**Comment by boblee0717** [comment]
@slinkydeveloper Thanks for your reply, I am considering to upgrade the spec version from 0.2 to 1.0.

**Comment by slinkydeveloper** [comment]
I think you can check out the differences here: https://github.com/cloudevents/spec/releases

Can we close this issue?
