### ISSUE TITLE
The spring-reactive example doesn't follow the http-protocol-binding spec

### ISSUE THREAD

**Issue by zhouxinyu** [cloudevents/sdk-java#334]
In the spring-reactive example, it shows the data in "structured" format:

```
curl -v -H'Content-type: application/cloudevents+json' \
    -d '{"data": {"value": "Foo"},
         "ce-id: 1,
         "ce-source": "cloud-event-example"
         "ce-type": "my.application.Foo"
         "ce-specversion": "1.0"}' \
    http://localhost:8080/event
```

While in the http-protocol-binding spec, it shows the structured mode:

```
PUT /myresource HTTP/1.1
Host: webhook.example.com
Content-Type: application/cloudevents+json; charset=utf-8
Content-Length: nnnn

{
    "specversion" : "1.0",
    "type" : "com.example.someevent",

    ... further attributes omitted ...

    "data" : {
        ... application data ...
    }
}
```

The example adds the prefix `ce-` to all cloudevents filed except `data`, is it just a documentation error?

**Comment by slinkydeveloper** [comment]
I think it's just documentation error, in the tests https://github.com/cloudevents/sdk-java/blob/master/spring/src/test/java/io/cloudevents/spring/webflux/WebFluxRestControllerTests.java#L93 it's a correct structured mode. But can you try to test it?

**Comment by slinkydeveloper** [comment]
cc @dsyer

**Comment by dsyer** [comment]
The example is wrong. The tests in the sample project verify that the behaviour is correct, I think. I'm happy for someone else to fix it and verify.

**Comment by dsyer** [comment]
Hasn't it already been fixed though?

**Comment by slinkydeveloper** [comment]
Yep, just checked, we're good now. Thanks for double checking!
