### ISSUE TITLE
Valid data filed according to dataschema field

### ISSUE THREAD

**Issue by renyijiu** [cloudevents/sdk-java#336]
Hello, thanks the great job of the project. I hava a question when i try to use the sdk.

If i set the dataschema field and then set the data field, will it valid the data field according the schema defined in dataschema field when i send the event through the sdk?

**Comment by pierDipi** [comment]
> If i set the dataschema field and then set the data field, will it valid the data field according the schema defined in dataschema field when i send the event through the sdk?

No, it won't validate the data field.

**Comment by renyijiu** [comment]
> > If i set the dataschema field and then set the data field, will it valid the data field according the schema defined in dataschema field when i send the event through the sdk?
> 
> No, it won't validate the data field.


Ok, thanks for the quick response. Any planning to support it? i don't know others may have the same needs

**Comment by slinkydeveloper** [comment]
> Any planning to support it? 

I think that's outside the scope of the project, for a multitude of reasons:

* data schema can contain any kind of schema (json schema, xsd, etc), so i guess we'll need to support a range of them. This also requires a validator abstraction, which is already available in a large number of java projects out there.
* depending on the validator implementation, you eventually need to convert the input to some data structure, which then might be wasted because the user will operate on another data structure
* it's not a concern of the marshaller/unmarshaller of cloudevent to validate the inner payload of the cloudevent. CloudEvent is the envelope, what you do with the payload is a user concern.

**Comment by pierDipi** [comment]
> i don't know others may have the same needs

If the community wants to build an integration, there shouldn't be a problem linking it in the docs (I guess) as long as it is open source and licensed under a compatible license.

**Comment by renyijiu** [comment]
> > Any planning to support it?
> 
> I think that's outside the scope of the project, for a multitude of reasons:
> 
> * data schema can contain any kind of schema (json schema, xsd, etc), so i guess we'll need to support a range of them. This also requires a validator abstraction, which is already available in a large number of java projects out there.
> * depending on the validator implementation, you eventually need to convert the input to some data structure, which then might be wasted because the user will operate on another data structure
> * it's not a concern of the marshaller/unmarshaller of cloudevent to validate the inner payload of the cloudevent. CloudEvent is the envelope, what you do with the payload is a user concern.

Thanks for the detailed explanation. Mandatory verification does have certain shortcomings according to your explanation. 

My starting point is when we create kinds of events, it will help others to understand data struct and process the data if we can get data structure through the dataschema. And if we can valid the data when send event so we can make sure the data struct always right.

**Comment by slinkydeveloper** [comment]
> My starting point is when we create kinds of events, it will help others to understand data struct and process the data if we can get data structure through the dataschema. And if we can valid the data when send event so we can make sure the data struct always right.

I think your use case is very valid, but I believe an abstraction of it doesn't really fit inside this project. For the reasons above explained, I mark this issue as wontfix, let me know any additional thoughts.

**Comment by renyijiu** [comment]
> > My starting point is when we create kinds of events, it will help others to understand data struct and process the data if we can get data structure through the dataschema. And if we can valid the data when send event so we can make sure the data struct always right.
> 
> I think your use case is very valid, but I believe an abstraction of it doesn't really fit inside this project. You could have a `CloudEventBuilder` impl in your code that wraps the original builders provided by this project and, when `build()` is executed, it can validate the payload.
> 
> For the reasons above explained, I mark this issue as wontfix, let me know any additional thoughts.

Ok, thanks, i will close the issue and just left the result of discussion let other people with the same needs find the document.
