### ISSUE TITLE
Different Formats

### ISSUE THREAD

**Issue by 2020testuser** [cloudevents/sdk-java#337]
Hi,
I'm using CloudEvents Java SDK. I'm getting the avro messages from Kafka in CloudEvent format. Since, avro is not supported in CloudEvents- sdk-java, could anyone please let me know how I can convert avro message to json and read them when I have the payload(body) in avro format. 

Appreciate if anyone can provide more details on this. Thanks!

**Comment by slinkydeveloper** [comment]
In order to read the Cloudevent as Avro message, you need an Avro EventFormat, which at the moment doesn't exist. I close this as it's a duplicate of #115

**Comment by 2020testuser** [comment]
@slinkydeveloper - Thanks! So, how can I get the data in byte array format and use it for further processing? Could you please shed some light of this? Thanks!
