### ISSUE TITLE
Formatting

### ISSUE THREAD

**Issue by 2020testuser** [cloudevents/sdk-java#338]
Hi,
Could anyone please help me?
I'm using CloudEvent and getting my avro data in byte[] format.
What is the best approach to convery my avro byte[] in json format? 
I see CloudEvent sdk-java doesn't support avro and so wondering what options I have?

Thanks in advance!

**Comment by slinkydeveloper** [comment]
> I'm using CloudEvent and getting my avro data in byte[] format.

Do you mean that the `data` field of the cloudevent contains avro, so the payload is avro? Or you mean that the full event is encoded as avro, per spec https://github.com/cloudevents/spec/blob/v1.0.1/avro-format.md

**Comment by 2020testuser** [comment]
@slinkydeveloper - Very sorry for the delay. I have the data field as avro in cloudevent. 
Wondering what options I have. Thanks!

**Comment by slinkydeveloper** [comment]
In that case, you need to manually get the bytes of the data with `getBytes()` and then manually invoke the avro deserializer

**Comment by slinkydeveloper** [comment]
We might add at some point some deserializer similar to the one we have for jackson, but we need the avro module first, as discussed in #115

**Comment by 2020testuser** [comment]
@slinkydeveloper - Thanks!
