### ISSUE TITLE
Support binary attributes (and Extensions)

### ISSUE THREAD

**Issue by JemDay** [cloudevents/sdk-java#351]
The cloud event specification allows for context attributes (and extensions) to have binary value - at present support for this type is not present in the CloudEvent Builder.

**Comment by slinkydeveloper** [comment]
As a first step, I think you should start from adding the `setExtension`/`getExtension` with binary value in the api interfaces https://github.com/cloudevents/sdk-java/tree/master/api/src/main/java/io/cloudevents
