### ISSUE TITLE
Invalid Kafka Binary event when content-type not provided

### ISSUE THREAD

**Issue by shnplr** [cloudevents/sdk-java#370]
The Kafka spec states in section 3: `If the content-type header is not present then the receiver uses structured mode with the JSON event format.`

Since the SDK allows a binary message with `data` to be generated without providing `dataContentType`, the assumption here is that consumers MUST assume this is a Structured event (even though its not).

Question
1. Should the spec be amended to allow receivers to detect content mode whenever content-type does not start with `application/cloudevents`.
2. Alternatively should the serialize SDK generate an error for Binary mode with `data` and no `content-type`?

**Comment by slinkydeveloper** [comment]
> If the content-type header is not present then the receiver uses structured mode with the JSON event format.

TBH I don't recall this particular sentence, but looking at it, it seems to me there are two conflicting sentences https://github.com/cloudevents/spec/blob/v1.0.1/kafka-protocol-binding.md#3-kafka-message-mapping:

> The receiver of the event can distinguish between the two content modes by inspecting the content-type Header of the Kafka message. If the header is present and its value is prefixed with the CloudEvents media type application/cloudevents, indicating the use of a known event format, the receiver uses structured mode, otherwise it defaults to binary mode.

And then:

> If the content-type header is not present then the receiver uses structured mode with the JSON event format.

I'm gonna open an issue in the spec repo

**Comment by shnplr** [comment]
I assume in the first paragraph, the key sentence is "If the header is present..."
But I agree the wording could be improved to avoid any suggested contradiction.

**Comment by slinkydeveloper** [comment]
@shnplr I've opened an issue https://github.com/cloudevents/spec/issues/812 and proposed 2 solutions, feel free to provide your input there.

**Comment by slinkydeveloper** [comment]
The conflicting sentence was removed from the spec: https://github.com/slinkydeveloper/spec/commit/c023f5c93d5f9ec2a6d8f45c123b280ef6ec2332

I'm going to close this issue because I think it's solved now, reopen if you need it.
