### ISSUE TITLE
Should we consider ce-datacontenttype header when no Content-Type HTTP header is informed?

### ISSUE THREAD

**Issue by ricardozanini** [cloudevents/sdk-java#371]
Hi!

Just a quick question. I see that we are considering the [HTTP header `Content-type`](https://github.com/cloudevents/sdk-java/blob/master/http/restful-ws/src/main/java/io/cloudevents/http/restful/ws/impl/CloudEventsHeaders.java#L30-L32)as the `ce-datacontenttype` attribute. It's a good thing, but I came up with certain scenarios where the message comes without the `Content-type` header, but only with `ce-datacontenttype`. In such scenarios, we might fail to serialize the message correctly.

**Comment by slinkydeveloper** [comment]
@ricardozanini the messages you're receiving are technically wrong per spec: https://github.com/cloudevents/spec/blob/v1.0.1/http-protocol-binding.md#311-http-content-type

**Comment by ricardozanini** [comment]
@slinkydeveloper, I know. Actually, the Knative Broker is sending messages like this. When I push an `application/json+cloudevents` message to it, the Broker broadcasts the message to my Triggers without the `Content-type` header. The CE SDK is then serializing the message using `BINARY` format, messing with my application. 

I'm about to open an issue there as well as soon as I have the time to work in a reproducer.

**Comment by slinkydeveloper** [comment]
That sounds like a different problem, which may be related to the sdk. Is there any chance you can share the full http envelope you're receiving in the sdk? http headers + body

**Comment by ricardozanini** [comment]
I don't think it's related to this SDK. I understand that the Knative Broker is not forwarding the `content-type` correctly when the message is a `cloudevents+json`. Although it is correctly parsing the CE. I put this gist together with a reproducer:
https://gist.github.com/ricardozanini/9d0652194db6738245fa4fcc566b543e

I think I'll open an issue for the Knative Eventing folks :)

**Comment by slinkydeveloper** [comment]
I think from this side, nothing else can be done, so I'm going to close this issue, reopen if you need it.
