### ISSUE TITLE
Publishing the CloudEvents-Protobuf artifact to Maven Central?

### ISSUE THREAD

**Issue by Antauri** [cloudevents/sdk-java#375]
Morning guys and great work,

Is it possible to publish the CloudEvents Protobuf artifact, part of the sdk-java to Maven Central?
It seems it's not there https://mvnrepository.com/artifact/io.cloudevents

I know it's a new module/code, only a week old but we immediately jumped on the idea of CE over Protobuf as envelope (plus an Smile/MsgPack/Protobuf or some other form of binary "data") and we want to use it as part of a few Java projects, directly from Maven Central without the need to build it locally.

Thank you kind sirs!

**Comment by slinkydeveloper** [comment]
Yep, this is going to be released as soon as 2.4 is going to be released

**Comment by Antauri** [comment]
Awesome. Just so we're aware, when is 2.1 estimated?

**Comment by slinkydeveloper** [comment]
There is no estimate. I'm going to do a triage of opened issues and PRs soon and then figure out if we're in a good shape to release

**Comment by slinkydeveloper** [comment]
Here you go https://github.com/cloudevents/sdk-java/releases/tag/2.1.0. Thanks again for your contribution!
