### ISSUE TITLE
JMS Adaptor

### ISSUE THREAD

**Issue by michaelandrepearce** [cloudevents/sdk-java#38]
Is there an adaptor/wrapper for JMS client, thus allowing easy plug and play with existing MoM solutions that support topics, without the need to make an adaptor for each specific one?

**Comment by fabiojose** [comment]
@michaelandrepearce No.

There is a discussion in the CNCF CloudEvents slack around this support.

Join us!

**Comment by slinkydeveloper** [comment]
I think such adaptor requires first a binding in the cloudevents spec, so I think you should open an issue on https://github.com/cloudevents/spec/issues

**Comment by slinkydeveloper** [comment]
I'm gonna close this, since it's related to the spec itself. When we have a proper protocol binding in our spec, we can reopen it and implement it here
