### ISSUE TITLE
Support CloudEvents Spec 0.3

### ISSUE THREAD

**Issue by mhyeon-lee** [cloudevents/sdk-java#39]
I wonder if java-sdk will support the CloudEvents 0.3 spec.

**Comment by linux-china** [comment]
* contenttype” attribute has been renamed to “datacontenttype
* Add subject attribute

If possible,  Java SDK could add extension constants in https://github.com/cloudevents/spec/tree/master/extensions  by default?

**Comment by hanoisteve** [comment]
So what is the status on this?

**Comment by avgcastillo** [comment]
@matzew do you know if there is active work on this topic, does this project need some help from new contributors?

**Comment by fabiojose** [comment]
Done in the PR https://github.com/cloudevents/sdk-java/pull/49

Waiting for the release.

**Comment by fabiojose** [comment]
Released!

Now available in version 0.3.0
