### ISSUE TITLE
Until Spec 0.3 support is available?

### ISSUE THREAD

**Issue by hanoisteve** [cloudevents/sdk-java#40]
Any suggestions on what do until 0.3 support is in place? What changes do we need to make. Also is it possible to use. https://github.com/protocolbuffers/protobuf/blob/master/java/util/src/main/java/com/google/protobuf/util/JsonFormat.java. ?

**Comment by fabiojose** [comment]
Done in the PR https://github.com/cloudevents/sdk-java/pull/49

Waiting for the release.

**Comment by fabiojose** [comment]
Available in the version 0.3.0
