### ISSUE TITLE
Provide a Bill of Materials for easier integration in projects

### ISSUE THREAD

**Issue by nvervelle** [cloudevents/sdk-java#404]
It would be nice to have BOM artifact for cloudevents to provide easier dependency management for projects using cloudevents (like [this](https://github.com/aws/aws-sdk-java-v2/tree/master/bom)).

I'm going to submit a PR for this one.

**Comment by dorongold** [comment]
@slinkydeveloper is this BOM published?
I cannot find cloudevents-bom on [maven central repository](https://search.maven.org/).

**Comment by nvervelle** [comment]
> @slinkydeveloper is this BOM published? I cannot find cloudevents-bom on [maven central repository](https://mvnrepository.com/artifact/io.cloudevents).

I think it's not published yet, it's in 2.3 which is not released yet...

**Comment by pierDipi** [comment]
2.3.0 is out https://github.com/cloudevents/sdk-java/releases/tag/2.3.0!

Try it and let us know if it works!

**Comment by nvervelle** [comment]
Seems to work, I only specify the version on the BOM :smile:
