### ISSUE TITLE
Examples for Spring Reactive with WebClient would be nice to have

### ISSUE THREAD

**Issue by salaboy** [cloudevents/sdk-java#417]
@dsyer I was looking at the examples provided here: https://github.com/cloudevents/sdk-java/blob/master/examples/spring-reactive/src/test/java/io/cloudevents/examples/spring/DemoApplicationTests.java 
And it will be great to have the test using WebClient instead of TestRestTemplate, I couldn't find any example showing how to send a CloudEvent (instead of returning a cloudevent) using WebClient which as far as I understand is the suggested client for reactive apps. 

Looking at WebClient, I can't do something like

```
HttpHeaders outgoing = CloudEventHttpUtils.toHttp(cloudEventBuilder.build());
webClient.post().headers(outgoing).body("").retrieve().bodyToMono(String.class);
```
As `headers()` doesn't take HttpHeaders. Which is kinda frustrating. 
I might be missing something here.. so any pointer is highly appreciated.

**Comment by dsyer** [comment]
But `headers()` takes a `Consumer<HttpHeaders>` doesn't it? So you can do this I guess: `headers(headers -> headers.putAll(outgoing))`. Here's what I tried in the `DemoApplicationTests`:

```java
    @Autowired
    private WebTestClient rest;

    @Test
    void echoWithCorrectHeaders() {

        rest.post().uri("/foos").header("ce-id", "12345") //
                .header("ce-specversion", "1.0") //
                .header("ce-type", "io.spring.event") //
                .header("ce-source", "https://spring.io/events") //
                .contentType(MediaType.APPLICATION_JSON) //
                .bodyValue("{\"value\":\"Dave\"}") //
                .exchange() //
                .expectStatus().isOk() //
                .expectHeader().exists("ce-id") //
                .expectHeader().exists("ce-source") //
                .expectHeader().exists("ce-type") //
                .expectHeader().value("ce-id", value -> {
                    if (value.equals("12345"))
                        throw new IllegalStateException();
                }) //
                .expectHeader().valueEquals("ce-type", "io.spring.event.Foo") //
                .expectHeader().valueEquals("ce-source", "https://spring.io/foos") //
                .expectBody(String.class).isEqualTo("{\"value\":\"Dave\"}");

    }
```

**Comment by salaboy** [comment]
@dsyer that works, it will be great to have that example in the test so people see how it can be done with WebClient

**Comment by dsyer** [comment]
See #418

**Comment by pierDipi** [comment]
Does https://github.com/cloudevents/sdk-java/pull/418 close this issue?

**Comment by dsyer** [comment]
I believe so.
