### ISSUE TITLE
Why extension key should be lowercase chars

### ISSUE THREAD

**Issue by ruanwenjun** [cloudevents/sdk-java#425]
Hi community, I find the extension key in cloudevents must be lowercase chars, cloudevents will check this.
I just have this question, since our system need to break this rule, so I want to ask why this design or can we avoid this?

**Comment by matejvasek** [comment]
spec:
>CloudEvents attribute names MUST consist of lower-case letters ('a' to 'z') or digits ('0' to '9') from the ASCII character set.

https://github.com/cloudevents/spec/blob/v1.0.1/spec.md#attribute-naming-convention

**Comment by ruanwenjun** [comment]
Thanks @matejvasek.
