### ISSUE TITLE
[snyk] Deserialization of Untrusted Data Affecting com.fasterxml.jackson.core:jackson-databind artifact, versions [,2.9.9.3)

### ISSUE THREAD

**Issue by cwallsfdc** [cloudevents/sdk-java#45]
Is there a process to resolve snyk raised vulnerabilities?

How to merge/PR the following snyk addressed PR?

https://github.com/cloudevents/sdk-java/pull/41

@fabiojose 

Thank you!

**Comment by fabiojose** [comment]
@cwallsfdc We have another one with the latest version of Jackson.

Fixed in PR #58
