### ISSUE TITLE
CLOMonitor Metadata

### ISSUE THREAD

**Issue by duglin** [cloudevents/sdk-java#453]
See: https://clomonitor.io/projects/cloudevents/cloudevents
Can we get the appropriate updates so that the CLOMonitor tool is happy?
More info on CLOMonitor checks: https://github.com/cncf/clomonitor/blob/main/docs/checks.md

**Comment by pierDipi** [comment]
Closing since it's green for sdk-java https://clomonitor.io/projects/cncf/cloudevents/cloudevents#sdk-java
