### ISSUE TITLE
2.4.0 breaks JSON Deserialization

### ISSUE THREAD

**Issue by fredoboulo** [cloudevents/sdk-java#481]
Hi,

We can't update io.cloudevents:cloudevents-json-jackson:2.3.0 to 2.4.0.

Our cloudEvents have a **datacontenttype** with value **application/json;charset=utf-8**, which leads to JSON deserialization error.
The [newly introduced Pattern in JsonFormat](https://github.com/cloudevents/sdk-java/blob/master/formats/json-jackson/src/main/java/io/cloudevents/jackson/JsonFormat.java#L50) does not take parameters into account.

Reading the spec, it seems a bit confusing

- [Payload Serialization](https://github.com/cloudevents/sdk-java/blob/master/formats/json-jackson/src/main/java/io/cloudevents/jackson/JsonFormat.java#L50) handles the parameters stripping
- [Payload Deserialization](https://github.com/cloudevents/spec/blob/v1.0.2/cloudevents/formats/json-format.md#312-payload-deserialization) is silent about parameters.

Would it be possible to enrich the pattern to take the parameters into account?

**Comment by pierDipi** [comment]
Hi @fredoboulo, thanks for reporting!

I think it makes sense what you're suggesting.

cc @JemDay @segator

**Comment by pierDipi** [comment]
@fredoboulo since nobody raised any concern so far, can you contribute this change to the SDK?

**Comment by segator** [comment]
Sorry for the delay guys I were on vacations with limited access to mail.
@pierDipi  so the idea is to support in the regex attributes like the charset one

`foo/barr;attr1=value&attr2=value... `?
