### ISSUE TITLE
Integration with Apache RocketMQ

### ISSUE THREAD

**Issue by aaron-ai** [cloudevents/sdk-java#494]
Hi, I am a contributor of Apache RocketMQ, since RocketMQ has been merge into the [proprietary part of the spec](https://github.com/cloudevents/spec/blob/main/cloudevents/proprietary-specs.md), could we provide a RocketMQ protocol binding implementation?

**Comment by aaron-ai** [comment]
If this aligns with the direction of the community, I am happy to contribute it.

**Comment by pierDipi** [comment]
Hi @aaron-ai, I'm ok with hosting the spec implementation here, however, since I'm not that familiar with RocketMQ, I might need help when issues are reported or when any kind of maintenance might be needed, would that work for you?

**Comment by aaron-ai** [comment]
> Hi @aaron-ai, I'm ok with hosting the spec implementation here, however, since I'm not that familiar with RocketMQ, I might need help when issues are reported or when any kind of maintenance might be needed, would that work for you?

Of course. I'm glad to be involved!
