### ISSUE TITLE
Snapshots repositories not in readme

### ISSUE THREAD

**Issue by salaboy** [cloudevents/sdk-java#50]
Currently the README.md points to version 0.3.0 which is not available in Maven Central.
I am assuming that there is a snapshot or nightly build repo where 0.3.0 can be found, 
it will be great to add that in the readme. 

In the mean time can someone point me to that repository?

**Comment by fabiojose** [comment]
@salaboy 

We are facing problems to release to maven central.

Now the version is already there: https://search.maven.org/search?q=g:io.cloudevents
