### ISSUE TITLE
Validation and (custom) extensions

### ISSUE THREAD

**Issue by black-snow** [cloudevents/sdk-java#516]
First of all, how do I validate that what I read follows the spec (in a certain version)? Is there something built in? Does it just throw on error?

Second, if there is a validation built in how can I extend it to also check for known or custom extensions? This would come in super handy.

**Comment by pierDipi** [comment]
> First of all, how do I validate that what I read follows the spec (in a certain version)? Is there something built in? Does it just throw on error?

Validation is built-in the CloudEventBuilder, any integration in the SDK uses the builder to create a CloudEvent instance. When an event is not valid, the builder throws a [`CloudEventRWException`](https://www.javadoc.io/static/io.cloudevents/cloudevents-api/2.4.1/io/cloudevents/rw/CloudEventRWException.html) that you can catch and act on it.

> Second, if there is a validation built in how can I extend it to also check for known or custom extensions? This would come in super handy.

That is left to the application layer and it isn't possible to attach custom validation logic.

**Comment by black-snow** [comment]
@pierDipi thanks. So The Builder will always validate against its version? What if I needed to support different (incompatible) versions of the spec?

**Comment by pierDipi** [comment]
> So The Builder will always validate against its version?

Yes.

> What if I needed to support different (incompatible) versions of the spec?

I think, there are no imcompatible versions, 0.3 and 1.0 are roundtrip-able (meaning that a cloudevent for version 0.3 can converted to 1.0 and the other way around too), so that problem doesn't exist as far as I know.

So you can do something like this:

```java
final CloudEvent ev1 = new io.cloudevents.core.v1.CloudEventBuilder()
    .withId(...)
    // etc ...
    .build()
  
final CloudEvent ev03 = io.cloudevents.core.v03.CloudEventBuilder(ev1).build()
```

**Comment by black-snow** [comment]
@pierDipi aight, thanks!
