### ISSUE TITLE
[protobuf] 'create' and 'read' aren't entirely symmetrical

### ISSUE THREAD

**Issue by pierDipi** [cloudevents/sdk-java#532]
> It's starting to come back to me now ... with respect to the data handling there's no guarantee that a receiving application/intermediary will be able to hydrate the actual ProtoBuf message from the data on reception, that's why the 'Any'  construct is returned so that the business app can do the appropriate type mapping if needed, or pass it on elsewhere if required.
>
> Granted this does mean the 'create' and 'read' aren't entirely symmetrical ..

_Originally posted by @JemDay in https://github.com/cloudevents/sdk-java/issues/523#issuecomment-1440827380_

**Comment by JemDay** [comment]
I can pick this up ... it'll be breaking change but a worthwhile one ...
