### ISSUE TITLE
Kafka Producer Factory

### ISSUE THREAD

**Issue by MartyTremblay** [cloudevents/sdk-java#54]
I'm trying to decide on whether a kafka producer factory would be helpful for the SDK? For now, I'll implement CloudEventsKafkaProducerFactory for my project but I can imagine that this could be useful for others.

**Comment by gunnarmorling** [comment]
Hey @MartyTremblay, can you elaborate a bit? How would that factory look like and how would it be used?

**Comment by slinkydeveloper** [comment]
I think this one is invalid for sdk v2, reopen if you need it
