### ISSUE TITLE
cloudevents-xml is not available on maven repository

### ISSUE THREAD

**Issue by astelmashenko** [cloudevents/sdk-java#551]
I see #448 is merged in Jan and latest release was in March. I tried to follow the docs https://cloudevents.github.io/sdk-java/xml.html
The dependency does not get resolved
```
<dependency>
    <groupId>io.cloudevents</groupId>
    <artifactId>cloudevents-xml</artifactId>
    <version>2.4.0</version>
</dependency>
```
I also can not find it on maven central.

**Comment by pierDipi** [comment]
xml is not yet released and it wasn't part of the 2.4 release https://github.com/cloudevents/sdk-java/tree/2.4/formats, unfortunately, our website is not versioned, so it shows docs for the main branch
