### ISSUE TITLE
Change type of source attribute from URI to String

### ISSUE THREAD

**Issue by gmuth** [cloudevents/sdk-java#601]
The source type should not be limited to URI.
https://github.com/cloudevents/sdk-java/blob/main/api/src/main/java/io/cloudevents/CloudEventAttributes.java

**Comment by pierDipi** [comment]
Can you expand on why?

`source` attribute in the is a URI-Reference type https://github.com/cloudevents/spec/blob/main/cloudevents/spec.md#source-1(type system https://github.com/cloudevents/spec/blob/main/cloudevents/spec.md#type-system)

**Comment by gmuth** [comment]
I missed that important bit. I thought the spec required string. So from a spec point of view it makes sense to keep URI.
However a lot of examples and explanations don't adhere to this type.
E.g.: https://spring.io/blog/2020/12/23/cloud-events-and-spring-part-2
So I guess for the sdk-java it's okay to strictly implement the spec.
The only argument I now find is resilience to support non-spec source values as well.

On the other hand I think string makes more sense - however this I would have to address to another audience.
