### ISSUE TITLE
cloud events sdk for java 17

### ISSUE THREAD

**Issue by abhupadh** [cloudevents/sdk-java#662]
How to use cloudevents for java 17 considering the javax is not supported?
Build is failing for various classes not available as well in version 2.x and above such as `CloudEventsImpl` and `extensions` package classes.
As can't use version 1.x due to non-compatibility of javax in java17 and internally many classes using this version in cloudevents sdk.
Please advise.

**Comment by pierDipi** [comment]
I'm using the SDK with Java 21 and I've used it with Java 17 in the past, can you describe how to reproduce your issue?

**Comment by abhupadh** [comment]
> I'm using the SDK with Java 21 and I've used it with Java 17 in the past, can you describe how to reproduce your issue?

Thanks. but I figured it out. The cloudevents-core package has all the required classes in version 4.0. Closing this issue.

However, it would be really helpful if you could see this issue with custom extensions. https://github.com/cloudevents/sdk-java/issues/667
