### ISSUE TITLE
Kafka binary content type not set

### ISSUE THREAD

**Issue by 51systems** [cloudevents/sdk-java#67]
According to the [Binary content mode spec](https://github.com/cloudevents/spec/blob/master/kafka-protocol-binding.md#321-content-type):

> For the binary mode, the header content-type property MUST be mapped directly to the CloudEvents datacontenttype attribute.

However, it appears that this header is not being set properly.

I'm not really sure what should be responsible for setting this header. It seems that the `HeaderMapper` is a good candidate, but it is not aware if the content mode is structured or not. It seems that the only thing that is aware of the content mode is the `Marshallers`, and this is where the content mode is set for the structured mode as well.

For example, something along the lines of:
```java
public static <T> EventStep<AttributesImpl, T, byte[], byte[]> 
		binary() {
			
	return 
		BinaryMarshaller.<AttributesImpl, T, byte[], byte[]>
		  builder()
			.map(AttributesImpl::marshal)
			.map(Accessor::extensionsOf)
			.map(ExtensionFormat::marshal)
			.map(HeaderMapper::map)
			.map(Json::binaryMarshal)
			.builder((payload, headers) -> {
				headers.putIfAbsent("content-type", headers.get("ce_datacontenttype"));
				return new Wire<>(payload, headers);
			});
}
```

Its also the case that only the ce_datacontenttype field is considered when unmarshalling, when the "content-type" field should probably be used.

**Comment by fabiojose** [comment]
You are right!

**Comment by 51systems** [comment]
If someone is able to provide guidance as to where this header should be set, I'm happy to submit a pull request.
