### ISSUE TITLE
Java SDK allows empty subject during deserialization

### ISSUE THREAD

**Issue by pnt** [cloudevents/sdk-java#676]
Hi,

[Specification](https://github.com/cloudevents/spec/blob/v1.0/spec.json) says that "subject" is optional but if present, must be non-empty.

Doing a simple test with structured or binary event delivery shows that this is not validated by the standard deserializers - the screenshot below shows how a test expecting a 400 Bad Request actually passes with 200 OK.
![image](https://github.com/user-attachments/assets/e691e73a-ffef-4f20-91e9-8efd58f176fe)

**Comment by pierDipi** [comment]
Would you be interested in contributing?

We need to update the 2 builders with the subject validation:
- https://github.com/cloudevents/sdk-java/blob/a3decf768c75e7e97924f8bb96b53f8b83c57739/core/src/main/java/io/cloudevents/core/v03/CloudEventBuilder.java#L117-L133
- https://github.com/cloudevents/sdk-java/blob/a3decf768c75e7e97924f8bb96b53f8b83c57739/core/src/main/java/io/cloudevents/core/v1/CloudEventBuilder.java#L113-L130

**Comment by pnt** [comment]
Yes, I’ll take a look at those. Along with tests, that should be it?
