### ISSUE TITLE
manage custom attributtes

### ISSUE THREAD

**Issue by alejandroa12** [cloudevents/sdk-java#77]
Dear team,
How can i handle custom attributes using json java sdk?
i need to work with something like this:
{
"specversion" : "1.0",
"type" : "com.example.someevent",
"source" : "/mycontext",
"id" : "A234-1234-1234",
"time" : "2018-04-05T17:31:00Z",
"Custom Attribute1" : "bar"
"Custom Attribute2" : "foo"
"datacontenttype" : "text/xml",
"data" : "<much wow="xml"/>"
}

and manage on the Cloud events object this custom attributes. like: 
CloudEventImpl cloudEvent = CloudEventBuilder.<Object>builder()
                .withType("Cloudevent")
                .withId("298262ed-eb85-4de7-95b3-efcd42d823d4")
                .withSource(URI.create("/EventManagementTest"))
                .withData("HELLO".getBytes())
                .withTime(dateNow)
                .withSubject("Cloud Event")
                .withDataContentType(URI.create("http://my.br").toString())
                .withDataschema(URI.create("application/json"))
                .withExtension(tracing)
                .withCustomAttribute(CUSTOM ATTRIBUTE)
                .build();

**Comment by fabiojose** [comment]
@alejandroa12, you must use extension for that.

You may create your own extension, like this:

Create a `CustomAttributeExtension`:

```java
      public class CustomAttributeExtension implements ExtensionFormat {

		private final Map<String, String> transport = new HashMap<>();
		private final InMemoryFormat inmemory;
		
		public CustomAttributeExtension(final String name, final String value) {
			transport.put(name, value);
			
			this.inmemory = new InMemoryFormat() {
				
				@Override
				public Class<?> getValueType() {
					return String.class;
				}
				
				@Override
				public Object getValue() {
					return value;
				}
				
				@Override
				public String getKey() {
					return name;
				}
			};
		}
		
		@Override
		public InMemoryFormat memory() {
			return inmemory;
		}

		@Override
		public Map<String, String> transport() {
			return transport;
		}
	}
```

Then, use it:

```java
      CustomAttributeExtension foo = new CustomAttributeExtension("Custom Attribute1", "foo");
      CustomAttributeExtension bar = new CustomAttributeExtension("Custom Attribute2", "bar");

      CloudEvent<AttributesImpl, Amount> event =
                CloudEventBuilder.<Amount>builder()
                        .withId(UUID.randomUUID().toString())
                        .withTime(ZonedDateTime.now())
                        .withDataContentType("application/cloudevent+json")
                        .withDataschema(new URI("structured_schema"))
                        .withSource(new URI("structured_source"))
                        .withSubject("structured_subject")
                        .withData(payload)
                        .withType("structured_type")
                        .withExtension(foo)
                        .withExtension(bar)
                        .build();
```

Resulting:

```json
{
    "data":{
        "a":1
    },
    "id":"0cb578ff-3898-45b6-9e9d-b6a0677d46c0",
    "source":"structured_source",
    "specversion":"1.0",
    "type":"structured_type",
    "datacontenttype":"application/cloudevent+json",
    "dataschema":"structured_schema",
    "subject":"structured_subject",
    "time":"2019-12-02T20:10:41.664-03:00",
    "Custom Attribute1":"foo",
    "Custom Attribute2":"bar"
}
```

**Comment by alejandroa12** [comment]
Thanks fabio, now I got this problem with the wire function. When I use the function the field data appears two times in the output so that brings me problems parsing the json object.

**Comment by fabiojose** [comment]
@alejandroa12 

We fixed this bug of data appearing two times in version 1.1.0.

**Comment by slinkydeveloper** [comment]
Hi @alejandroa12, with sdk v2 (you can try the 2.0.0-SNAPSHOT) you can easily access the extensions just doing `event.getExtensions().get("myattribute")`. You don't need anymore a way to access extensions creating an extension pojo.

BTW the extension name `Custom Attribute1` is invalid for the spec: https://github.com/cloudevents/spec/blob/v1.0/spec.md#attribute-naming-convention

**Comment by xbblq62** [comment]
@fabiojose 

Can you please let me know how you are able to print the event as below
{
    "data":{
        "a":1
    },
    "id":"0cb578ff-3898-45b6-9e9d-b6a0677d46c0",
    "source":"structured_source",
    "specversion":"1.0",
    "type":"structured_type",
    "datacontenttype":"application/cloudevent+json",
    "dataschema":"structured_schema",
    "subject":"structured_subject",
    "time":"2019-12-02T20:10:41.664-03:00",
    "Custom Attribute1":"foo",
    "Custom Attribute2":"bar"
}

when i try to print using objectmapper i am getting as below:
{
	"data": {
		"empty": false,
		"present": true
	},
	"id": "843ef433-d2f9-4fb1-928f-da60000633cd",
	"source": "DTR",
	"specversion": "0.3",
	"type": "twin-messaging.lwm2m.request",
	"time": {
		"empty": true,
		"present": false
	},
	"schemaurl": {
		"empty": true,
		"present": false
	},
	"datacontenttype": {
		"empty": true,
		"present": false
	},
	"subject": {
		"empty": true,
		"present": false
	},
	"datacontentencoding": {
		"empty": true,
		"present": false
	},
	"message_type": "LWM2M_READ"
}
