### ISSUE TITLE
Wrong email in Maven meta-data

### ISSUE THREAD

**Issue by jponge** [cloudevents/sdk-java#84]
https://github.com/cloudevents/sdk-java/blob/6861823eb8dbcee7f58ea2abcd5b1c33e9077bc6/pom.xml#L53

This is not my email 😉

**Comment by fabiojose** [comment]
@jponge 

Could you perform a PR to fix it?

**Comment by jponge** [comment]
Sure :-)

**Comment by jponge** [comment]
See #92
