### ISSUE TITLE
data_base64 and data both set for binary data

### ISSUE THREAD

**Issue by cookingkode** [cloudevents/sdk-java#85]
CloudEventBuilder.build() sets both data_base64 and data in case data is of binary type.  This is a duplication / bloat of payload . Shouldn't they be mutually exclusive?

**Comment by fabiojose** [comment]
@cookingkode 

Could you provide an example of resulting payload?

**Comment by slinkydeveloper** [comment]
This should be fixed with 2.0.0-SNAPSHOT, reopen if you need it
