### ISSUE TITLE
Kafka binary content type not read

### ISSUE THREAD

**Issue by 51systems** [cloudevents/sdk-java#88]
#67 fixed the problem where the kafka `content-type` header is not written. However, it appears `io.cloudevents.v1.kafka.AttributeMapper` does not attempt to read the content type from the appropriate header (doesn't attempt to read content type from `content-type` header).

**Comment by bsideup** [comment]
@fabiojose I can work on this (and add missing tests), how do you assign `help wanted` tasks?

**Comment by slinkydeveloper** [comment]
I think this one now should just work with v2, reopen if you need it
