### ISSUE TITLE
BinaryUnmarshaller confused by charset in Content-Type

### ISSUE THREAD

**Issue by eamonnmcmanus** [cloudevents/sdk-java#89]
BinaryUnmarshaller expects the Content-Type to be exactly `application/json`. It fails if the Content-Type is `application/json; charset=utf-8`, as it is in [this example from the spec](https://github.com/cloudevents/spec/blob/v1.0/http-protocol-binding.md#314-examples).

**Comment by slinkydeveloper** [comment]
This should be fixed in 2.0.0-SNAPSHOT, reopen if you need it
