### ISSUE TITLE
CloudEvents prefix for extension attributes in Kafka headers

### ISSUE THREAD

**Issue by pdalbora** [cloudevents/sdk-java#93]
The Java SDK does not currently prefix extension attributes with "ce_" in the headers. 

[Section 3.2.3.1 of the specification for Kafka Protocol Binding](https://github.com/cloudevents/spec/blob/v1.0/kafka-protocol-binding.md#3231-property-names) states that "CloudEvent attributes are prefixed with ce_ for use in the message-headers section." While the specification does not _explicitly_ state either way whether this applies also to extension attributes, I can't see a good reason why they would be treated differently.

Is the different treatment of extension attributes in the SDK intentional, or do you agree that they should also be prefixed with "ce_"?

**Comment by fabiojose** [comment]
We aggree @pdalbora, they must be prefixed.

**Comment by bsideup** [comment]
Is there some soft of a TCK for the spec?

**Comment by slinkydeveloper** [comment]
I think this one should work with 2.0.0-SNAPSHOT, reopen if you need it
