### ISSUE TITLE
Should CDI & Vert.x support be removed from core SDK

### ISSUE THREAD

**Issue by ojhughes** [cloudevents/sdk-java#95]
As a core SDK, would it make more sense that any concrete implementations live in their own Github projects? That way the cloudevents implementations could reside under their parents Github org such as `vertx-3/vertx-cloudevents` and attract a wider audience. Also removes maintenance burden from the core project.

**Comment by slinkydeveloper** [comment]
I think it's fine to have several integrations with various frameworks as soon as they are modular from the core package.
We plan to add even more as you see here https://github.com/cloudevents/sdk-java/projects/1
