### ISSUE TITLE
Should remove bean validations from core SDK

### ISSUE THREAD

**Issue by fabiojose** [cloudevents/sdk-java#96]
To provide a dependency-free SDK that can be used with a variety of frameworks and different versions.

I want to propose to remove the bean validations.

**Comment by cwallsfdc** [comment]
@fabiojose, we're running up against dependency conflicts w/ `org.hibernate.validator` which also brings in several other conflicting dependencies.  This prevents us from upgrading to Cloudevent 1.0.

Is there a plan to replace `org.hibernate.validator`  bean validation or removing altogether?  Anyway to accelerate an alternative?  We're happy to discuss and help.

**Comment by slinkydeveloper** [comment]
Solved by #108
